<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ taglib uri="http://java.sun.com/jstl/core_rt" prefix="c" %>



<h2>Step 1. Create a file 'pom.xml'</h2>

<p>
	This example project is a Maven`s project. It means that the application is built by using	 
	<a href="explanations/apache_maven" class='dialogLink' 
		>Apache Maven</a>
	tool which deals with such issues like external dependencies, 
	other components necessary for the project or the build order.  								
</p>

<p>
	Maven projects are configured by using a Project Object Model, which is stored in a file called <b>pom.xml</b>.
	This file should be placed in the main folder of the project and it looks like this:
</p>

<div class="code">
	<pre class="brush: xml;">
		<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
								
								
			<groupId>pl.kwi</groupId>
			<artifactId>HelloWorldServlets</artifactId>
			<version>1.0</version>
			<packaging>war</packaging>
			<modelVersion>4.0.0</modelVersion>
			<name>&#36;{artifactId}</name>
		
		
			<build>
			
				<finalName>&#36;{artifactId}</finalName>
				
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<configuration>
							<source>1.5</source>
							<target>1.5</target>
						</configuration>
					</plugin>
				</plugins>
				
			</build>
		
		
			<dependencies>
				
				<!-- Servlets dependencies -->
				<dependency>
					<groupId>javax.servlet</groupId>
					<artifactId>servlet-api</artifactId>
					<version>2.3</version>
					<scope>provided</scope>
				</dependency>
				
				<!-- JSP dependencies -->
				<dependency>
					<groupId>jstl</groupId>
					<artifactId>jstl</artifactId>
					<version>1.0.6</version>
				</dependency>
				<dependency>
					<groupId>taglibs</groupId>
					<artifactId>standard</artifactId>
					<version>1.0.6</version>
				</dependency>
				
			</dependencies>
		
		</project>
	</pre>
	<div>File 'pom.xml'</div>
</div>





<h2>Step 2. Create a file 'web.xml'</h2>

<p>
	In	
	<a href="explanations/java_servlets_technology" class='dialogLink' 
		>Java Servlets Technology</a> 
	the file <b>web.xml</b> is called 'web descriptor'. This file is always 
	placed in a folder <b>webapp/WEB-INF</b>. Its` main task is mapping/connecting
	the specified <b>url-pattern</b> from the user`s browser with the appropriate <b>servlet-name</b> 
	and this <b>servlet-name</b> with the appropriate <b>servlet-class</b>.  
</p>

<p>
	In our case, for instance, when the url from the user`s browser ends with the sentence <b>/hello.do</b> 
	<i>(line 13)</i> then browser`s request is redirected to the Servlet called <b>HelloServlet</b> 
	<i>(line 12)</i>. And the Servlet called <b>HelloServlet</b> is connected with the class 
	<b>pl.kwi.helloworldservlets.servlets.HelloServlet</b> <i>(lines 8 and 9)</i>. 
</p>

<p>
	The file <b>web.xml</b> for our example web application should look like this:
</p>

<div class="code">
	<pre class="brush: xml;">							
		<?xml version="1.0" encoding="UTF-8"?>
		<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
				 xmlns="http://java.sun.com/xml/ns/javaee" 
				 xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" 
				 xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" 
				 id="WebApp_ID" 
				 version="2.5">
		
			<display-name>HelloWorldServlets</display-name>
				
			<servlet>
				<servlet-name>HelloServlet</servlet-name>
				<servlet-class>pl.kwi.helloworldservlets.servlets.HelloServlet</servlet-class>
			</servlet>
			<servlet-mapping>
				<servlet-name>HelloServlet</servlet-name>
				<url-pattern>/hello.do</url-pattern>
			</servlet-mapping>
				
			<servlet>
				<servlet-name>WelcomeServlet</servlet-name>
				<servlet-class>pl.kwi.helloworldservlets.servlets.WelcomeServlet</servlet-class>
			</servlet>
			<servlet-mapping>
				<servlet-name>WelcomeServlet</servlet-name>
				<url-pattern>/welcome.do</url-pattern>
			</servlet-mapping>
			
			
			<welcome-file-list>		
				<welcome-file>/index.jsp</welcome-file>		
			</welcome-file-list>
			
		</web-app>							
	</pre>
	<div>File 'web.xml'</div>
</div>




<h2>Step 3. Create a Jsp file 'helloJsp.jsp'</h2>

<p>
	In our example application every single 
	<a href="explanations/html" class='dialogLink'>HTML</a> 
	page connected with specified Servlet is dynamically generated by using 
	<a href="explanations/jsp" class='dialogLink'>JSP</a> 
	technology. 
</p>

<p>
	The file <b>helloJsp.jsp</b> from the folder <b>webapp/jsp</b> is responsible for sending
	user`s name to the web application. The user can type his name in the field <b>userName</b> <i>(line 29)</i> 
	which is part of the bigger html element called <b>form</b> <i>(lines from 19 to 36)</i>. 
</p>	

<p>	
	The button 'Ok' <i>(line 32)</i> submits this whole form to the web application. 
	Moreover, the form`s action is automatically added at the end of the url - in this case  
	<b>hello.do</b> <i>(line 19)</i>.				  
</p>

<div class="code">
	<pre class="brush: xml;">							
		&lt;!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

		&lt;%@ page language="java" contentType="text/html; charset=utf-8"
			pageEncoding="utf-8"%>
		
		&lt;html>
		
		
		&lt;head>
			<title>Hello World Servlets</title>
			<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
			<script type="text/javascript" src="scripts/script.js"></script>
			<link type="text/css" rel="stylesheet" href="styles/style.css">
		&lt;/head>
		
		
		&lt;body>
		<form action="hello.do">
		
			<table align="center" frame="border" class="mainTable">
				<tr>
					<td>
						<h2>Hello World Servlets</h2>
						<h3>Page: <b>Hello</b></h3>
					</td>
				</tr>
				<tr>
					<td>Type your name:	<input type="text" id="userName" name="userName" size="10"/></td>
				</tr>
				<tr>
					<td><input type="submit" id="submit" name="submit" value="OK"/></td>
				</tr>		
			</table>
			
		</form>
		&lt;/body>
		
		
		&lt;/html>							
	</pre>
	<div>File 'helloJsp.jsp'</div>
</div>





<h2>Step 4. Create Servlet 'HelloServlet.java'</h2>

<p>
	The Servlet class <b>HelloServlet</b> from the package <b>pl.kwi.helloworldservlets.servlets</b> 
	is responsible for handling the user`s request with his name. The web descriptor <b>web.xml</b>
	redirects requests from <b>helloJsp.jsp</b> to this servlet basing on his own mapping.				  
</p>

<p>
	Servlet <b>HelloServlet</b> takes parameter <b>userName</b> from request <i>(line 21)</i> and
	puts it as request`s attribute with the same name <i>(line 22)</i>. Then servlet
	forwards this request to page <b>welcomeJsp.jsp</b> <i>(lines 24 and 25)</i>.  
</p>

<div class="code">
	<script type="syntaxhighlighter" class="brush: java"><![CDATA[
		package pl.kwi.helloworldservlets.servlets;

		import java.io.IOException;
		
		import javax.servlet.RequestDispatcher;
		import javax.servlet.ServletException;
		import javax.servlet.http.HttpServlet;
		import javax.servlet.http.HttpServletRequest;
		import javax.servlet.http.HttpServletResponse;
		
		public class HelloServlet extends HttpServlet{
			
			
			private static final long serialVersionUID = 1L;
			
			
			@Override
			public void service(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
						
				String userName = request.getParameter("userName");
				request.setAttribute("userName", userName);
				
				RequestDispatcher requestDispatcher = request.getRequestDispatcher("jsp/welcomeJsp.jsp");
				requestDispatcher.forward(request, response);		
				
			}	
		
		}
	]]></script>
	<div>File 'HelloServlet.java'</div>
</div>