DROP TABLE IF EXISTS article_tags;

GO

CREATE TABLE article_tags (
  ID BIGINT(20) NOT NULL auto_increment,
  UNIQUE_NAME VARCHAR(100) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

GO