DROP TABLE IF EXISTS join_article_and_tag;

GO

CREATE TABLE join_article_and_tag (
  ARTICLE_ID INT(10) UNSIGNED NOT NULL,
  ARTICLE_TAG_ID INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (ARTICLE_ID, ARTICLE_TAG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

GO